In [7]:
import pandas as pd
import numpy as np

In [2]:
path = 'C:/Users/trmyi/Desktop/AI_class/project/house_prediction/'
#https://data.gov.tw/dataset/137371 READ DESCRIPTIONS OF COLUMNS
df = pd.read_csv(path+'housepropertydata_v2.csv')

In [4]:
df = df.drop(columns=['Unnamed: 0'])

In [5]:
df1_columns = ['District', 'MainMaterial', 'B_area', 'LivingR', 'BathR', 'Price',
       'PropertyType2']
df1 = df[df1_columns]
df2 = pd.get_dummies(df1)

In [6]:
df2_x = df2.drop(columns=['Price'])
df2_y = df2[['Price']]

In [21]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.tree import DecisionTreeRegressor


def find_best_model_using_gridsearchcv(X,y):
    algos = {
        'linear_regression' : {
            'model': LinearRegression(),
            'params': {
                'normalize': [True,False]
            }
        },
        'lasso': {
            'model': Lasso(),
            'params': {
                'alpha': [1,2],
                'selection': ['random', 'cyclic']
            }
        },
        'decision_tree': {
            'model': DecisionTreeRegressor(),
            'params': {
                'criterion' : ['squared_error','friedman_mse'],
                'splitter': ['best','random']
            }
        }
    }
    scores = []
    cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
    for algo_name, config in algos.items():
        gs =  GridSearchCV(config['model'], config['params'], cv=cv, return_train_score=False)
        gs.fit(X,y)
        scores.append({
            'model': algo_name,
            'best_score': gs.best_score_,
            'best_params': gs.best_params_
        })

    return pd.DataFrame(scores,columns=['model','best_score','best_params'])



In [22]:
from warnings import simplefilter
from sklearn.exceptions import ConvergenceWarning
simplefilter("ignore", category=ConvergenceWarning)
find_best_model_using_gridsearchcv(df2_x,df2_y)

c:\users\trmyi\desktop\ai_class\project\house_prediction\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(
c:\users\trmyi\desktop\ai_class\project\house_prediction\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previou

model  best_score  \
0  linear_regression    0.728278   
1              lasso    0.728115   
2      decision_tree    0.671765   

                                         best_params  
0                               {'normalize': False}  
1                {'alpha': 2, 'selection': 'cyclic'}  
2  {'criterion': 'friedman_mse', 'splitter': 'ran...

In [24]:
df1.head()

District MainMaterial  B_area  LivingR  BathR       Price PropertyType2
0      中和區       鋼筋混凝土造   89.65        1      2  13900000.0          住宅大樓
1      新店區       鋼筋混凝土造  103.21        2      2   5000000.0            公寓
2      中和區       鋼筋混凝土造   57.60        1      1   4500000.0            公寓
3      八里區       鋼筋混凝土造  120.18        1      1   5350000.0            華廈
4      蘆洲區       鋼筋混凝土造   98.32        1      2   9500000.0            公寓

In [ ]:
''''def predict_price(location,sqft,bath,bhk):    
    loc_index = np.where(X.columns==location)[0][0]

    x = np.zeros(len(X.columns))
    x[0] = sqft
    x[1] = bath
    x[2] = bhk
    if loc_index >= 0:
        x[loc_index] = 1

    return lr_clf.predict([x])[0]

In [43]:
loc_index = np.where(df1.columns=='District')[0][0]
loc_index

0

In [44]:
x = np.zeros(len(df1.columns))
x

array([0., 0., 0., 0., 0., 0., 0.])

In [45]:
x[0] = 5
x[1] = 6
x[2] = 7
x

array([5., 6., 7., 0., 0., 0., 0.])

In [46]:
[x]

[array([5., 6., 7., 0., 0., 0., 0.])]

In [47]:
if loc_index >= 0:
        x[loc_index] = 1

In [48]:
x

array([1., 6., 7., 0., 0., 0., 0.])